### ISSUE TITLE
Extension of a test with an import

### ISSUE THREAD

**Issue by Xtravaganz** [benmccann/svelte-jest-add-example#1]
Extension of the current example:
```

<script>
	import Router from 'svelte-routing';
</script>

<Router>
</Router>
```

Error:
**({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export { default as Router } from "./Router.svelte";**

It would perhaps help me and others if an example with an import was added here.
I am new to this area at the moment and I would be happy to see a practical example here.

**Comment by benmccann** [comment]
This was just meant to be a short-lived example for discussion purposes. It's not a repo I'm maintaining
